folders:
  - folder_path: "odin"
    description: "odin service job"
jobs:
    - job_path: "odin/build_job"
      jenkinsfile_git_repo: "https://github.com/mkshkmrgpt/odin.git"
      jenkinsfile_path: "Jenkinsfile"
      auto_trigger: true