folders:
  - folder_path: "odin"
    description: "odin service job"
  - folder_path: "asgard"
    description: "asgard cluster provision job"
  - folder_path: "bifrost"
    description: "bifrost mapping jobs"
jobs:
    - job_path: "odin/build_job"
      jenkinsfile_git_repo: "https://github.com/mkshkmrgpt/odin.git"
      jenkinsfile_path: "Jenkinsfile"
      auto_trigger: true
    - job_path: "asgard/cluster"
      jenkinsfile_git_repo: "https://github.com/mkshkmrgpt/asgard-infrastructure.git"
      jenkinsfile_path: "Jenkinsfile"
      auto_trigger: true
    - job_path: "asgard/alb-and-dns"
      jenkinsfile_git_repo: "https://github.com/mkshkmrgpt/asgard-infrastructure.git"
      jenkinsfile_path: "exercise3/app-dns-and-alb/alb_dns_pipeline"
      auto_trigger: true
    - job_path: "bifrost/alb"
      jenkinsfile_git_repo: "https://github.com/mkshkmrgpt/bifrost-mapping.git"
      jenkinsfile_path: "alb-and-dns/Jenkinsfile"
      auto_trigger: true
    - job_path: "bifrost/cluster-and-service"
      jenkinsfile_git_repo: "https://github.com/mkshkmrgpt/bifrost-mapping.git"
      jenkinsfile_path: "Jenkinsfile"
      auto_trigger: true